# Site Settings
title: Arts For Hearts
description: 
url: http://ArtsForHearts.github.io/
donateLink: http://www2.heart.org/site/TR?pg=team&fr_id=2432&team_id=186110

# Build Settings
markdown: kramdown
permalink: pretty
